version: '3'

services:
  affine:
    image: ghcr.io/toeverything/affine-self-hosted:latest
    volumes:
      - ../docker_volumes/affine/app:/app/data
    restart: unless-stopped
    ports:
      - 3000:3000